### PR TITLE
Integrate Mayhem

### PR DESCRIPTION
**Pull request by rnshah9**

### CODE REVIEW

**Review by xansec — CHANGES_REQUESTED** [review]
Something seems wrong with this one as well (https://mayhem.forallsecure.com/rnshah9/pycopy/pycopy/4), it's possible that there is a better way to send fuzzed input to this target. Please make the requested changes.

**Comment by rnshah9** [comment]
I'm getting the same issue even when I try to fuzz the binary [in REPL mode](https://mayhem.forallsecure.com/rnshah9/pycopy/pycopy/9); in Mayhem, nearly every test case is a crashing test case but I can't reproduce the crash when running the test case locally in a Docker container.

I can't see any stdout/stderr Mayhem logs either for debugging. The event log seems fine.

**Comment by xansec** [comment]
Looking at this more closely - is this just a Python interpreter? I don't expect fuzzing to be particularly interesting in this case. I do notice a `tests/` dir here that may have more relevant/interesting test cases, but as it stands fuzzing an interpreter (or a compiler), while can occasionally be interesting, is usually not useful or effective (most test cases will be thrown away by the lexer).

**Comment by rnshah9** [comment]
There is indeed a good variety of test cases in that folder, and even without it Mayhem is able to discover quite a few. But even when I upload the corpus, every test case is still (spuriously?) crashing the binary.

**Comment by xansec** [comment]
Sorry, I meant to say that we should use the unit tests under `/tests` as bases for fuzzing harnesses. The python interpreter is throwing away most inputs that are not valid python and exiting with 1, such as:

```
root@8a2e046ba72c:/# echo test > test
root@8a2e046ba72c:/# ./pycopy test
Traceback (most recent call last):
  File "test", line 1, in <module>
NameError: name 'test' isn't defined
root@8a2e046ba72c:/# echo $?
1
```
This is not very interesting. A harness based on some of the modules exposed under the unit tests would likely discover more interesting behavior.

**Comment by rnshah9** [comment]
Hmm, I'm still not clear on what you mean. I'm only seeing a bunch of test `.py` files and some Python scripts to run them through the same `pycopy` binary and compare them to some expected output. Harnessing those scripts would be identical to the current behavior, I think--could you give an example of the kind of module you'd like to see harnessed?

**Comment by rnshah9** [comment]
Bump on this

**Comment by xansec** [comment]
See the integration for micropython here:
https://github.com/mayhemheroes/micropython/pull/2/files#diff-9bb2346f245f1620fcde4a99925baac2ebca0d2d2957dfbf38937b9476f77b4f
This was based off of the following example:
https://github.com/micropython/micropython/blob/6e71cde6aad2b2ed3d431d8d94c9bd2ee52e319d/examples/embedding/hello-embed.c

There are similar examples in this project, such as :
https://github.com/mayhemheroes/pycopy/blob/master/examples/usercmodule/cppexample/examplemodule.c

Of course you may select whatever you like.

**Comment by xansec** [comment]
Please review and see if any new harnesses can be added, otherwise this will be closed due to inactivity.

**Comment by rnshah9** [comment]
I appreciate the pointers. Unfortunately, though, I don't think I have time to see this one through right now.

**Pull request closed without merging**
